name: Deploy Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: localhost:5000/mysql:latest
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: img_txt_project
          MYSQL_USER: root

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Push API Image
        run: |
          docker build -t localhost:5000/api:latest ./api
          docker push localhost:5000/api:latest

      - name: Build and Push Model Image
        run: |
          docker build -t localhost:5000/model:latest ./model
          docker push localhost:5000/model:latest

      - name: Deploy with Docker Compose
        run: |
          docker-compose up -d

          # Sleep for a while to allow containers to start
          sleep 30

          # Add any necessary steps for database migrations or other initialization
          # Example: docker-compose exec api python manage.py migrate

      - name: Test Deployment
        run: |
          docker-compose exec api pytest

      - name: Tear Down Deployment
        run: |
          docker-compose down

